### ISSUE TITLE
Build fails if AliRoot available

### ISSUE THREAD

**Issue by matthiasrichter** [AliceO2Group/AliceO2#369]
The O2 build fails if AliRoot is enabled

```bash
Linking CXX executable ../../bin/runHough
/src/src/alisw/sw/ubuntu1604_x86-64/AliRoot/a37e2ef6e99e54923b24792e86ae3e60c24384b6_O2-1/lib/libAliHLTTPC.so: undefined reference to `AliOptionParser::ProcessOptionString(TStrin
g)'
collect2: error: ld returned 1 exit status
Utilities/hough/CMakeFiles/runHough.dir/build.make:105: recipe for target 'bin/runHough' failed
```

TODO:
- [x] correct the recipe (https://github.com/alisw/alidist/issues/742)
- [x] make AliRoot ctest working (https://github.com/alisw/AliRoot/issues/187)
- [x] fix conditional build of `AliOptionParser` in AliRoot (https://github.com/alisw/AliRoot/issues/189)

**Comment by Barthelemy** [comment]
Didn't we agreed to remove AliRoot as dependency of O2 ? I think that it was during a CWG13.

**Comment by matthiasrichter** [comment]
yes, we did. This was mainly about the recipe.

Right now AliRoot is not removed from O2 yet, and in fact it makes sense to have it optional (thinking again about handling of legacy stuff).

In this perspective the O2 build fails if AliRoot is included in the build session. This is not the default but possible.

**Comment by graffaele** [comment]
I agree with Matthias, it would be very useful to keep the option to build AliRoot and O2 together.

Policies apart, I could overcome the error reported by Matthias, despite removing "AliRoot" from "disable" in defaults-o2, but at the price of hacking a bit of AliRoot code.

**Comment by matthiasrichter** [comment]
I haven't checked so far, it looks like that some new functionality has been introduced which creates another hidden dependency. The HLT libraries always had the information about their dependencies. I suspect that this needs to be updated. Easy to fix if this is the case. I will check.

**Comment by graffaele** [comment]
The required symbol is not defined in libAliHLTUtil because AliZMQhelpers stays in the if(ZEROMQ_FOUND) section, which is not executed. I extracted from AliZMQhelpers all the zmq-indipendent part and added that class in SRCS. For me that was the solution. In my opinion either iit makes sense to do the same in AliRoot, if part of these helpers should be provided independently from zmq being found, or in O2 we should care to avoid to refer to symbols which are provided by that class.

**Comment by matthiasrichter** [comment]
thanks, I was mislead by the name of the missing symbol and thought it is some general AliRoot function. Indeed it's code in HLT which is only build if ZeroMQ is available. Then it should be very easy to fix in the build recipe. I'm running a test now.

**Comment by matthiasrichter** [comment]
Thanks to Raffaele's hint I could locate the problem quite quickly, however there are a couple of issues at the same time. I'm adding those as action items to the original post

**Comment by matthiasrichter** [comment]
last item fixed in https://github.com/alisw/AliRoot/pull/419
